version: "3"
services:
  globaleaks:
    image: ckeeney/docker-globaleaks
    build: .
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/var:/var/globaleaks
# noop for rebuild